import React from "react";
import { useFormContext } from "react-hook-form";
import type { ShipmentFormValues } from "./formTypes";

export const SchemaFields: React.FC = () => {
  const { register, formState: { errors } } = useFormContext<ShipmentFormValues>();

  return (
    <div className="flex flex-col gap-3.5 p-4 rounded-xl bg-[#f8fafc] border border-[#e5e8ee]">
      <div>
        <h3 className="text-xs font-bold text-[#003356]">Backend Shipment References</h3>
        <p className="text-[10px] text-[#72777f] mt-0.5">Optional IDs can be supplied when the shipment is linked to existing fleet records.</p>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <Field label="Vehicle ID" error={errors.vehicleId?.message}>
          <input
            {...register("vehicleId")}
            placeholder="MongoDB vehicle ID"
            className="w-full h-10 px-3 rounded-lg bg-white text-xs font-semibold text-[#181c20] border border-[#e5e8ee] focus:border-[#174a73] focus:outline-none"
          />
        </Field>
        <Field label="Driver ID" error={errors.driverId?.message}>
          <input
            {...register("driverId")}
            placeholder="MongoDB driver ID"
            className="w-full h-10 px-3 rounded-lg bg-white text-xs font-semibold text-[#181c20] border border-[#e5e8ee] focus:border-[#174a73] focus:outline-none"
          />
        </Field>
        <Field label="Route ID" error={errors.routeId?.message}>
          <input
            {...register("routeId")}
            placeholder="MongoDB route ID"
            className="w-full h-10 px-3 rounded-lg bg-white text-xs font-semibold text-[#181c20] border border-[#e5e8ee] focus:border-[#174a73] focus:outline-none"
          />
        </Field>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <Field label="Shipment Status" error={errors.status?.message}>
          <select {...register("status")} className="w-full h-10 px-3 rounded-lg bg-white text-xs font-semibold text-[#181c20] border border-[#e5e8ee] focus:border-[#174a73] focus:outline-none">
            <option value="PENDING">Pending</option>
            <option value="ASSIGNED">Assigned</option>
            <option value="IN_TRANSIT">In Transit</option>
            <option value="DELIVERED">Delivered</option>
            <option value="CANCELLED">Cancelled</option>
          </select>
        </Field>
        <div className="sm:col-span-2 rounded-lg border border-dashed border-[#cfe4ff] bg-white px-3 py-2 text-[10px] text-[#72777f]">
          <strong className="block text-[#003356]">Generated by the backend</strong>
          imageUrl and imagePublicId are created from the required driver image upload. The route snapshot is created from the selected origin and destination.
        </div>
      </div>
    </div>
  );
};

interface FieldProps {
  label: string;
  error?: string;
  children: React.ReactNode;
}

const Field: React.FC<FieldProps> = ({ label, error, children }) => (
  <label className="flex flex-col gap-1.5">
    <span className="text-xs font-semibold text-[#181c20]">{label}</span>
    {children}
    {error && <span className="text-[10px] text-rose-600">{error}</span>}
  </label>
);
